version: "3.8"
services:
  mysql:
    image: mysql:8.0.21
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tasks
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - TZ=America/Mexico_City
    command: --default-authentication-plugin=mysql_native_password
  app:
    container_name: tasks-api
    image: tasks-api
    working_dir: /app
    env_file: 
      - .env
    build:
      context: .
    volumes: 
      - .:/app
    ports:
      - "3000:3000"
    command: > 
      sh -c 'npm i 
      && rm -rf dist
      && npm run build
      && npm run start:dev'
    depends_on: 
      - mysql
